### ISSUE TITLE
Pip subprocess error while set up environment for micom

### ISSUE THREAD

**Issue by mutantjoo0** [micom-dev/paper#3] opened 2020-04-30 22:01 UTC
Hello,
I am trying to install MICOM to analyze metabolic network in my 16 amplicon sequencing data. I got errors while setting up conda environment for micom. FYI, I copied and pasted from terminal.

#check conda
```
(base) -bash-4.2$ conda info

     active environment : base
    active env location : /mnt/home/leejooy5/miniconda3
            shell level : 1
       user config file : /mnt/home/leejooy5/.condarc
 populated config files : /mnt/home/leejooy5/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.17
       base environment : /mnt/home/leejooy5/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /mnt/home/leejooy5/miniconda3/pkgs
                          /mnt/home/leejooy5/.conda/pkgs
       envs directories : /mnt/home/leejooy5/miniconda3/envs
                          /mnt/home/leejooy5/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/3.10.0-957.5.1.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 925536:2019
             netrc file : None
           offline mode : False
```

#download micom
```
(base) -bash-4.2$ git clone https://github.com/micom-dev/paper
Cloning into 'paper'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 307 (delta 3), reused 7 (delta 2), pack-reused 292
Receiving objects: 100% (307/307), 51.57 MiB | 19.34 MiB/s, done.
Resolving deltas: 100% (158/158), done.
(base) -bash-4.2$ ls -lht
total 885M
drwxr-x---  6 leejooy5 mmg 8.0K Apr 28 22:47 paper

```
#change directory name
```
(base) -bash-4.2$ mv ./paper ./MICOM 
(base) -bash-4.2$ pwd && ls
/mnt/home/leejooy5/MICOM
data  figures  LICENSE  micom.yml  process.R  README.md  Snakefile  workflows

```

#setup environment
```
(base) -bash-4.2$ conda env create -f micom.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
boto3-1.12.48        | 69 KB     | ############################################################################## | 100%
rsa-4.0              | 27 KB     | ############################################################################## | 100%
idna_ssl-1.1.0       | 6 KB      | ############################################################################## | 100%
prettytable-0.7.2    | 15 KB     | ############################################################################## | 100%
snakemake-minimal-5. | 159 KB    | ############################################################################## | 100%
typing_extensions-3. | 38 KB     | ############################################################################## | 100%
gitdb-4.0.4          | 46 KB     | ############################################################################## | 100%
pyasn1-modules-0.2.7 | 60 KB     | ############################################################################## | 100%
pygraphviz-1.5       | 118 KB    | ############################################################################## | 100%
networkx-2.4         | 1.2 MB    | ############################################################################## | 100%
protobuf-3.11.4      | 699 KB    | ############################################################################## | 100%
ncbi-ngs-sdk-2.10.4  | 141 KB    | ############################################################################## | 100%
mpich-3.3.2          | 6.4 MB    | ############################################################################## | 100%
ghostscript-9.22     | 18.1 MB   | ############################################################################## | 100%
pyqt-5.12.3          | 6.3 MB    | ############################################################################## | 100%
pytest-5.4.1         | 379 KB    | ############################################################################## | 100%
ftputil-3.4          | 37 KB     | ############################################################################## | 100%
libblas-3.8.0        | 10 KB     | ############################################################################## | 100%
markupsafe-1.1.1     | 26 KB     | ############################################################################## | 100%
pickleshare-0.7.5    | 13 KB     | ############################################################################## | 100%
google-cloud-storage | 57 KB     | ############################################################################## | 100%
jedi-0.17.0          | 806 KB    | ############################################################################## | 100%
ipython-7.13.0       | 1.1 MB    | ############################################################################## | 100%
tqdm-4.45.0          | 48 KB     | ############################################################################## | 100%
pynacl-1.3.0         | 1.5 MB    | ############################################################################## | 100%
yaml-0.2.4           | 82 KB     | ############################################################################## | 100%
jmespath-0.9.5       | 20 KB     | ############################################################################## | 100%
google-auth-1.14.1   | 54 KB     | ############################################################################## | 100%
liblapack-3.8.0      | 10 KB     | ############################################################################## | 100%
giflib-5.1.7         | 455 KB    | ############################################################################## | 100%
libclang-9.0.1       | 22.3 MB   | ############################################################################## | 100%
wcwidth-0.1.9        | 20 KB     | ############################################################################## | 100%
python-libsbml-exper | 39.2 MB   | ############################################################################## | 100%
joypy-0.2.2          | 11 KB     | ############################################################################## | 100%
ruamel.yaml.clib-0.2 | 156 KB    | ############################################################################## | 100%
backcall-0.1.0       | 13 KB     | ############################################################################## | 100%
pandas-1.0.3         | 11.1 MB   | ############################################################################## | 100%
pyasn1-0.4.8         | 53 KB     | ############################################################################## | 100%
parso-0.7.0          | 67 KB     | ############################################################################## | 100%
hdmedians-0.13       | 158 KB    | ############################################################################## | 100%
dropbox-9.4.0        | 345 KB    | ############################################################################## | 100%
google-cloud-core-1. | 24 KB     | ############################################################################## | 100%
gdk-pixbuf-2.36.12   | 591 KB    | ############################################################################## | 100%
yarl-1.3.0           | 133 KB    | ############################################################################## | 100%
seaborn-0.10.1       | 158 KB    | ############################################################################## | 100%
ld_impl_linux-64-2.3 | 616 KB    | ############################################################################## | 100%
multidict-4.7.5      | 69 KB     | ############################################################################## | 100%
py-1.8.1             | 66 KB     | ############################################################################## | 100%
descartes-1.1.0      | 7 KB      | ############################################################################## | 100%
libwebp-1.0.2        | 939 KB    | ############################################################################## | 100%
gitpython-3.1.1      | 335 KB    | ############################################################################## | 100%
librsvg-2.44.14      | 10.6 MB   | ############################################################################## | 100%
google-resumable-med | 31 KB     | ############################################################################## | 100%
pip-20.1             | 1.1 MB    | ############################################################################## | 100%
pysftp-0.2.9         | 15 KB     | ############################################################################## | 100%
brotlipy-0.7.0       | 346 KB    | ############################################################################## | 100%
google-api-core-1.17 | 83 KB     | ############################################################################## | 100%
libstdcxx-ng-9.2.0   | 4.5 MB    | ############################################################################## | 100%
xz-5.2.5             | 430 KB    | ############################################################################## | 100%
pexpect-4.8.0        | 79 KB     | ############################################################################## | 100%
paramiko-2.7.1       | 283 KB    | ############################################################################## | 100%
pkg-config-0.29.2    | 122 KB    | ############################################################################## | 100%
psutil-5.7.0         | 324 KB    | ############################################################################## | 100%
scipy-1.4.1          | 18.9 MB   | ############################################################################## | 100%
natsort-7.0.1        | 32 KB     | ############################################################################## | 100%
cython-0.29.17       | 2.2 MB    | ############################################################################## | 100%
libffi-3.2.1         | 47 KB     | ############################################################################## | 100%
imagemagick-7.0.8_54 | 2.5 MB    | ############################################################################## | 100%
glib-2.64.2          | 3.4 MB    | ############################################################################## | 100%
prompt-toolkit-3.0.5 | 232 KB    | ############################################################################## | 100%
configargparse-1.2.3 | 29 KB     | ############################################################################## | 100%
jinja2-2.11.2        | 93 KB     | ############################################################################## | 100%
filechunkio-1.8      | 5 KB      | ############################################################################## | 100%
ptyprocess-0.6.0     | 15 KB     | ############################################################################## | 100%
packaging-20.1       | 31 KB     | ############################################################################## | 100%
zstd-1.4.4           | 991 KB    | ############################################################################## | 100%
pygments-2.6.1       | 683 KB    | ############################################################################## | 100%
openssl-1.1.1g       | 2.1 MB    | ############################################################################## | 100%
qt-5.12.5            | 99.2 MB   | ############################################################################## | 100%
openjpeg-2.3.1       | 475 KB    | ############################################################################## | 100%
docutils-0.15.2      | 736 KB    | ############################################################################## | 100%
nspr-4.25            | 1.6 MB    | ############################################################################## | 100%
fftw-3.3.8           | 6.0 MB    | ############################################################################## | 100%
palettable-3.3.0     | 86 KB     | ############################################################################## | 100%
xmlrunner-1.7.7      | 11 KB     | ############################################################################## | 100%
matplotlib-3.2.1     | 6 KB      | ############################################################################## | 100%
aioeasywebdav-2.4.0  | 18 KB     | ############################################################################## | 100%
python-3.6.10        | 34.1 MB   | ############################################################################## | 100%
libopenblas-0.3.9    | 7.8 MB    | ############################################################################## | 100%
async-timeout-3.0.1  | 11 KB     | ############################################################################## | 100%
sra-tools-2.10.3     | 50.8 MB   | ############################################################################## | 100%
_libgcc_mutex-0.1    | 3 KB      | ############################################################################## | 100%
mizani-0.6.0         | 52 KB     | ############################################################################## | 100%
libcblas-3.8.0       | 10 KB     | ############################################################################## | 100%
urllib3-1.25.9       | 92 KB     | ############################################################################## | 100%
nss-3.47             | 1.9 MB    | ############################################################################## | 100%
bcrypt-3.1.7         | 43 KB     | ############################################################################## | 100%
cairo-1.16.0         | 1.5 MB    | ############################################################################## | 100%
msgpack-python-1.0.0 | 91 KB     | ############################################################################## | 100%
botocore-1.15.48     | 3.8 MB    | ############################################################################## | 100%
mpi-1.0              | 4 KB      | ############################################################################## | 100%
libcroco-0.6.13      | 138 KB    | ############################################################################## | 100%
smmap-3.0.2          | 22 KB     | ############################################################################## | 100%
libprotobuf-3.11.4   | 4.8 MB    | ############################################################################## | 100%
wheel-0.34.2         | 24 KB     | ############################################################################## | 100%
cachecontrol-0.12.6  | 18 KB     | ############################################################################## | 100%
plotnine-0.6.0       | 3.3 MB    | ############################################################################## | 100%
aiohttp-3.6.2        | 605 KB    | ############################################################################## | 100%
hdf5-1.10.5          | 3.1 MB    | ############################################################################## | 100%
sqlite-3.30.1        | 2.0 MB    | ############################################################################## | 100%
scikit-bio-0.5.6     | 1.3 MB    | ############################################################################## | 100%
pango-1.40.14        | 528 KB    | ############################################################################## | 100%
cachetools-3.1.1     | 11 KB     | ############################################################################## | 100%
pytz-2020.1          | 227 KB    | ############################################################################## | 100%
libxkbcommon-0.10.0  | 475 KB    | ############################################################################## | 100%
s3transfer-0.3.3     | 90 KB     | ############################################################################## | 100%
cryptography-2.9.2   | 613 KB    | ############################################################################## | 100%
jbig-2.1             | 43 KB     | ############################################################################## | 100%
python-irodsclient-0 | 69 KB     | ############################################################################## | 100%
nbformat-5.0.6       | 99 KB     | ############################################################################## | 100%
lz4-c-1.9.2          | 223 KB    | ############################################################################## | 100%
pluggy-0.12.0        | 18 KB     | ############################################################################## | 100%
snakemake-5.15.0     | 6 KB      | ############################################################################## | 100%
setuptools-46.1.3    | 653 KB    | ############################################################################## | 100%
gobject-introspectio | 1.2 MB    | ############################################################################## | 100%
python-dateutil-2.8. | 220 KB    | ############################################################################## | 100%
zlib-1.2.11          | 105 KB    | ############################################################################## | 100%
lockfile-0.12.2      | 11 KB     | ############################################################################## | 100%
_openmp_mutex-4.5    | 5 KB      | ############################################################################## | 100%
readline-8.0         | 441 KB    | ############################################################################## | 100%
llvm-openmp-10.0.0   | 2.8 MB    | ############################################################################## | 100%
matplotlib-base-3.2. | 7.1 MB    | ############################################################################## | 100%
joblib-0.14.1        | 198 KB    | ############################################################################## | 100%
googleapis-common-pr | 64 KB     | ############################################################################## | 100%
libllvm9-9.0.1       | 25.1 MB   | ############################################################################## | 100%
crc32c-2.0           | 31 KB     | ############################################################################## | 100%
ruamel.yaml-0.16.6   | 166 KB    | ############################################################################## | 100%
libgcc-ng-9.2.0      | 8.2 MB    | ############################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/mnt/home/leejooy5/miniconda3/envs/micom/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/cdiener/nxviz (from -r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3))
  Cloning https://github.com/cdiener/nxviz to /tmp/pip-req-build-h1r3vxxs
Collecting git+https://github.com/micom-dev/micom (from -r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4))
  Cloning https://github.com/micom-dev/micom to /tmp/pip-req-build-777vqtfn
Collecting cobra
  Downloading cobra-0.17.1-py2.py3-none-any.whl (1.9 MB)
Collecting adjustText
  Downloading adjustText-0.7.3.tar.gz (7.5 kB)
Requirement already satisfied, skipping upgrade: cryptography>=2.1.4 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2.9.2)
Requirement already satisfied, skipping upgrade: pandas>=0.22.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (1.0.3)
Requirement already satisfied, skipping upgrade: matplotlib>=2.2.0 in /mnt/ufs18/home-041/leejooy5/.local/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2.2.4)
Requirement already satisfied, skipping upgrade: palettable>=3.1.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (3.3.0)
Requirement already satisfied, skipping upgrade: networkx>=2.0 in /mnt/ufs18/home-041/leejooy5/.local/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2.3)
Requirement already satisfied, skipping upgrade: setuptools>=38.6.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (46.1.3.post20200325)
Requirement already satisfied, skipping upgrade: numpy>=1.14.2 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (1.18.1)
Requirement already satisfied, skipping upgrade: PyYAML>=3.12 in /mnt/ufs18/home-041/leejooy5/.local/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (5.1.1)
Requirement already satisfied, skipping upgrade: seaborn>=0.8.1 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (0.10.1)
Collecting optlang>=1.4.4
  Downloading optlang-1.4.4-py2.py3-none-any.whl (125 kB)
Requirement already satisfied, skipping upgrade: tqdm>=4.14 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from micom==0.11.2->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4)) (4.45.0)
Collecting loguru>=0.3.2
  Downloading loguru-0.4.1-py3-none-any.whl (54 kB)
Collecting loky>=2.6.0
  Downloading loky-2.6.0-py2.py3-none-any.whl (63 kB)
Requirement already satisfied, skipping upgrade: jinja2>=2.10.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from micom==0.11.2->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4)) (2.11.2)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.22.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from micom==0.11.2->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4)) (0.22.2.post1)
Requirement already satisfied, skipping upgrade: scipy>=1.0.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from micom==0.11.2->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4)) (1.4.1)
Collecting fastcluster>=1.1.0
  Downloading fastcluster-1.1.26-cp36-cp36m-manylinux1_x86_64.whl (154 kB)
Collecting umap-learn>=0.4.1
  Downloading umap-learn-0.4.1.tar.gz (68 kB)
Requirement already satisfied, skipping upgrade: ruamel.yaml>=0.16 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from cobra->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 1)) (0.16.6)
Collecting swiglpk
  Downloading swiglpk-4.65.1-cp36-cp36m-manylinux1_x86_64.whl (627 kB)
Collecting python-libsbml-experimental==5.18.0
  Downloading python_libsbml_experimental-5.18.0-cp36-cp36m-manylinux1_x86_64.whl (43.9 MB)
Requirement already satisfied, skipping upgrade: six in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from cobra->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 1)) (1.14.0)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting depinfo
  Downloading depinfo-1.5.3-py2.py3-none-any.whl (8.7 kB)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from cryptography>=2.1.4->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (1.14.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from pandas>=0.22.0->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from pandas>=0.22.0->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2020.1)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from matplotlib>=2.2.0->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (1.2.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from matplotlib>=2.2.0->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (0.10.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from matplotlib>=2.2.0->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2.4.7)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in /mnt/ufs18/home-041/leejooy5/.local/lib/python3.6/site-packages (from networkx>=2.0->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (4.4.0)
Collecting sympy>=1.0.0
  Downloading sympy-1.5.1-py2.py3-none-any.whl (5.6 MB)
Collecting aiocontextvars>=0.2.0; python_version < "3.7"
  Downloading aiocontextvars-0.2.2-py2.py3-none-any.whl (4.9 kB)
Collecting cloudpickle
  Downloading cloudpickle-1.4.0-py3-none-any.whl (25 kB)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from jinja2>=2.10.0->micom==0.11.2->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4)) (1.1.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from scikit-learn>=0.22.0->micom==0.11.2->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 4)) (0.14.1)
Collecting numba!=0.47,>=0.46
  Downloading numba-0.49.0-cp36-cp36m-manylinux2014_x86_64.whl (3.6 MB)
Collecting tbb>=2019.0
  Downloading tbb-2020.0.133-py2.py3-none-manylinux1_x86_64.whl (933 kB)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from ruamel.yaml>=0.16->cobra->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 1)) (0.2.0)
Collecting pipdeptree>=0.13.2
  Downloading pipdeptree-0.13.2-py3-none-any.whl (16 kB)
Requirement already satisfied, skipping upgrade: pycparser in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4->nxviz==0.3.6->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 3)) (2.20)
Collecting mpmath>=0.19
  Downloading mpmath-1.1.0.tar.gz (512 kB)
Collecting contextvars==2.4; python_version < "3.7"
  Downloading contextvars-2.4.tar.gz (9.6 kB)
Collecting llvmlite<=0.33.0.dev0,>=0.31.0.dev0
  Downloading llvmlite-0.32.0-cp36-cp36m-manylinux1_x86_64.whl (20.2 MB)
Requirement already satisfied, skipping upgrade: pip>=6.0.0 in /mnt/ufs18/home-041/leejooy5/miniconda3/envs/micom/lib/python3.6/site-packages (from pipdeptree>=0.13.2->depinfo->cobra->-r /mnt/ufs18/home-041/leejooy5/MICOM/condaenv.5wv0s7rm.requirements.txt (line 1)) (20.1)
Collecting immutables>=0.9
  Downloading immutables-0.12-cp36-cp36m-manylinux1_x86_64.whl (97 kB)
Building wheels for collected packages: adjustText, nxviz, micom, umap-learn, future, mpmath, contextvars
  Building wheel for adjustText (setup.py): started
  Building wheel for adjustText (setup.py): finished with status 'done'
  Created wheel for adjustText: filename=adjustText-0.7.3-py3-none-any.whl size=7097 sha256=863309e41112d186515d5096bfc5e3dd153c25996e635259b19546877e7f267f
  Stored in directory: /mnt/ufs18/home-041/leejooy5/.cache/pip/wheels/70/86/f9/89161c891b07f90e2b15b5e4b6dfe70cc8f54c5ef26c0116f1
  Building wheel for nxviz (setup.py): started
  Building wheel for nxviz (setup.py): finished with status 'done'
  Created wheel for nxviz: filename=nxviz-0.3.6-py3-none-any.whl size=12511 sha256=c8deb8f4844125a3240b5cc9a8809f2e993f423c16eaaadedc0bcf0e9e754cf1
  Stored in directory: /tmp/pip-ephem-wheel-cache-uf0y1n90/wheels/2b/66/c5/9d4e9818a51cd3f912e275f1191b2f511f18f9fec161222acb
  Building wheel for micom (setup.py): started
  Building wheel for micom (setup.py): finished with status 'done'
  Created wheel for micom: filename=micom-0.11.2-py2.py3-none-any.whl size=139613 sha256=dfabe1f716cf907d0dd62e0b21ff4654f034db1f293fae4ba62d2c37d730841c
  Stored in directory: /tmp/pip-ephem-wheel-cache-uf0y1n90/wheels/dd/ba/fe/80f0b360a8ae6c0cad7c884f890ec3f350578dd84341a86554
  Building wheel for umap-learn (setup.py): started
  Building wheel for umap-learn (setup.py): finished with status 'done'
  Created wheel for umap-learn: filename=umap_learn-0.4.1-py3-none-any.whl size=66311 sha256=7ba452749bbcf01ed8cc4cbbf2a4cfd6bff64554ed676a5dc23d95799d742473
  Stored in directory: /mnt/ufs18/home-041/leejooy5/.cache/pip/wheels/4f/33/2b/cac60097e0150b2d53bd02e9a46fff7919cd2b0b9e1dd6d5a1
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=71a059c0e914a886d471369628916b6e7ad5031a2f2b13408eff1a89adcfcd4e
  Stored in directory: /mnt/ufs18/home-041/leejooy5/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
  Building wheel for mpmath (setup.py): started
  Building wheel for mpmath (setup.py): finished with status 'done'
  Created wheel for mpmath: filename=mpmath-1.1.0-py3-none-any.whl size=532239 sha256=5bcd5e7a63918c98d4b9a52dc9ad3e27f9e8c53b1d09e5464a641ab81e704ab9
  Stored in directory: /mnt/ufs18/home-041/leejooy5/.cache/pip/wheels/e8/38/69/aa17553ad31f09ff5fa44c8a1a6c5b47e7c9261e9c7c16b9fb
  Building wheel for contextvars (setup.py): started
  Building wheel for contextvars (setup.py): finished with status 'done'
  Created wheel for contextvars: filename=contextvars-2.4-py3-none-any.whl size=7664 sha256=9a9c273a0cf361cc8f4a9f987513ed1ce8154199359693bfed816e092a561e4d
  Stored in directory: /mnt/ufs18/home-041/leejooy5/.cache/pip/wheels/41/11/53/911724983aa48deb94792432e14e518447212dd6c5477d49d3
Successfully built adjustText nxviz micom umap-learn future mpmath contextvars
Installing collected packages: swiglpk, mpmath, sympy, optlang, python-libsbml-experimental, future, pipdeptree, depinfo, cobra, adjustText, nxviz, immutables, contextvars, aiocontextvars, loguru, cloudpickle, loky, fastcluster, llvmlite, numba, tbb, umap-learn, micom
  Attempting uninstall: python-libsbml-experimental
    Found existing installation: python-libsbml-experimental 5.18.1

Pip subprocess error:
  Running command git clone -q https://github.com/cdiener/nxviz /tmp/pip-req-build-h1r3vxxs
  Running command git clone -q https://github.com/micom-dev/micom /tmp/pip-req-build-777vqtfn
ERROR: multiqc 1.7 requires click, which is not installed.
ERROR: multiqc 1.7 requires markdown, which is not installed.
ERROR: Cannot uninstall 'python-libsbml-experimental'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.


CondaEnvException: Pip failed

```

**Comment by cdiener** [comment] 2020-05-01 00:06
Did you already have an environment called "micom" before? It seems like there are conflicts already installed packages... Also this repository is for reproducing the paper. In general it will be overkill and the normal micom package or the Qiime 2 plugin are more usable.

**Comment by mutantjoo0** [comment] 2020-05-01 01:35
No, I am new to micom. I am using another program on conda as follows:
```
# conda environments:
#
base                     /mnt/home/leejooy5/miniconda3
anvio-6.1                /mnt/home/leejooy5/miniconda3/envs/anvio-6.1
anvio-6.2                /mnt/home/leejooy5/miniconda3/envs/anvio-6.2
micom                 *  /mnt/home/leejooy5/miniconda3/envs/micom
```
Is this link "https://micom-dev.github.io/micom/ " normal micom that you meant ? I will try it.

**Comment by cdiener** [comment] 2020-05-01 04:16
Yes! That one is the pure Python version. This one will also receive a simpler API by next week that makes it easier to analyze several samples in parallel. Meanwhile I will investigate what happened with the conda environment. I am still a little confused about the `multiqc` error since that is not a dependency in the environment file.

**Comment by cdiener** [comment] 2020-05-06 00:53
Okay, that was my bad. There was an error in `micom.yml`. It should be fixed now.

**Closed as completed by cdiener** 2020-05-06 00:53 UTC
